// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Rfc3161Schema Timestamp Schema
//
// # Schema for RFC 3161 timestamp objects
//
// swagger:model rfc3161Schema
type Rfc3161Schema interface{}
