// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TufV001Schema TUF v0.0.1 Schema
//
// # Schema for TUF metadata entries
//
// swagger:model tufV001Schema
type TufV001Schema struct {

	// metadata
	// Required: true
	Metadata *TufV001SchemaMetadata `json:"metadata"`

	// root
	// Required: true
	Root *TufV001SchemaRoot `json:"root"`

	// TUF specification version
	// Read Only: true
	SpecVersion string `json:"spec_version,omitempty"`
}

// Validate validates this tuf v001 schema
func (m *TufV001Schema) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoot(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TufV001Schema) validateMetadata(formats strfmt.Registry) error {

	if err := validate.Required("metadata", "body", m.Metadata); err != nil {
		return err
	}

	if m.Metadata != nil {
		if err := m.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *TufV001Schema) validateRoot(formats strfmt.Registry) error {

	if err := validate.Required("root", "body", m.Root); err != nil {
		return err
	}

	if m.Root != nil {
		if err := m.Root.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("root")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("root")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this tuf v001 schema based on the context it is used
func (m *TufV001Schema) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRoot(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSpecVersion(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TufV001Schema) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	if m.Metadata != nil {

		if err := m.Metadata.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *TufV001Schema) contextValidateRoot(ctx context.Context, formats strfmt.Registry) error {

	if m.Root != nil {

		if err := m.Root.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("root")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("root")
			}
			return err
		}
	}

	return nil
}

func (m *TufV001Schema) contextValidateSpecVersion(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "spec_version", "body", string(m.SpecVersion)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TufV001Schema) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TufV001Schema) UnmarshalBinary(b []byte) error {
	var res TufV001Schema
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TufV001SchemaMetadata TUF metadata
//
// swagger:model TufV001SchemaMetadata
type TufV001SchemaMetadata struct {

	// Specifies the metadata inline within the document
	// Required: true
	Content interface{} `json:"content"`
}

// Validate validates this tuf v001 schema metadata
func (m *TufV001SchemaMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContent(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TufV001SchemaMetadata) validateContent(formats strfmt.Registry) error {

	if m.Content == nil {
		return errors.Required("metadata"+"."+"content", "body", nil)
	}

	return nil
}

// ContextValidate validates this tuf v001 schema metadata based on context it is used
func (m *TufV001SchemaMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TufV001SchemaMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TufV001SchemaMetadata) UnmarshalBinary(b []byte) error {
	var res TufV001SchemaMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TufV001SchemaRoot root metadata containing about the public keys used to sign the manifest
//
// swagger:model TufV001SchemaRoot
type TufV001SchemaRoot struct {

	// Specifies the metadata inline within the document
	// Required: true
	Content interface{} `json:"content"`
}

// Validate validates this tuf v001 schema root
func (m *TufV001SchemaRoot) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContent(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TufV001SchemaRoot) validateContent(formats strfmt.Registry) error {

	if m.Content == nil {
		return errors.Required("root"+"."+"content", "body", nil)
	}

	return nil
}

// ContextValidate validates this tuf v001 schema root based on context it is used
func (m *TufV001SchemaRoot) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TufV001SchemaRoot) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TufV001SchemaRoot) UnmarshalBinary(b []byte) error {
	var res TufV001SchemaRoot
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
